const caesar = require("./caesar");

test("'GUR DHVPX OEBJA QBT WHZCRQ BIRE GUR YNML SBK.' is 'THE QUICK BROWN DOG JUMPED OVER THE LAZY FOX.'", () => {
  expect(
    caesar.decrypt("GUR DHVPX OEBJA QBT WHZCRQ BIRE GUR YNML SBK.", 39)
  ).toBe("THE QUICK BROWN DOG JUMPED OVER THE LAZY FOX.");
});

test("'THE QUICK BROWN DOG JUMPED OVER THE LAZY FOX.' is 'GUR DHVPX OEBJA QBT WHZCRQ BIRE GUR YNML SBK.'", () => {
  expect(
    caesar.encrypt("THE QUICK BROWN DOG JUMPED OVER THE LAZY FOX.", 39)
  ).toBe("GUR DHVPX OEBJA QBT WHZCRQ BIRE GUR YNML SBK.");
});
